# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [19]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [20]:
### [your code here]
print("NumPy Version:", np.__version__)
print ("NumPy configuration:", np.show_config())

NumPy Version: 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    na

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [21]:
### [your code here]
a = np.random.random((2, 3, 5))
a1 = np.random.rand(2, 3, 5)
a2 = np.random.randint(0, 100, size=(2, 3, 5))



### 4. Print a.


In [22]:
### [your code here]
print(a)


[[[0.47390215 0.17515797 0.61892728 0.92184846 0.36711341]
  [0.09697434 0.97069412 0.97264883 0.36063071 0.47675032]
  [0.12272062 0.44136392 0.86437622 0.33154656 0.67765695]]

 [[0.36862302 0.50863563 0.12811749 0.51188969 0.19308622]
  [0.47621652 0.85555011 0.8421437  0.19447226 0.39324206]
  [0.52466284 0.37262377 0.77747227 0.66431809 0.13433683]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [23]:
### [your code here]
b = np.ones((5,2, 3))


### 6. Print b.


In [24]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [25]:
### [your code here]
is_same_size = a.shape == b.shape
print("Are a and b the same size?", is_same_size)

Are a and b the same size? False



### 8. Are you able to add a and b? Why or why not?


In [26]:
### [your code here]
# No, because two arrays have different dimensions



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [27]:
### [your code here]
c = b.transpose(1, 2, 0)
print("Transposed b:")
print(c)

Transposed b:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [28]:
### [your code here]
d = a + c
print("Result of a + c:")
print(d)

#because two arrays dimensions are compatible

Result of a + c:
[[[1.47390215 1.17515797 1.61892728 1.92184846 1.36711341]
  [1.09697434 1.97069412 1.97264883 1.36063071 1.47675032]
  [1.12272062 1.44136392 1.86437622 1.33154656 1.67765695]]

 [[1.36862302 1.50863563 1.12811749 1.51188969 1.19308622]
  [1.47621652 1.85555011 1.8421437  1.19447226 1.39324206]
  [1.52466284 1.37262377 1.77747227 1.66431809 1.13433683]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [29]:
### [your code here]
print ("the array a", a)
print ("the array d", d)
# every single number in d is exactly 1 greater than the corresponding number in a.

the array a [[[0.47390215 0.17515797 0.61892728 0.92184846 0.36711341]
  [0.09697434 0.97069412 0.97264883 0.36063071 0.47675032]
  [0.12272062 0.44136392 0.86437622 0.33154656 0.67765695]]

 [[0.36862302 0.50863563 0.12811749 0.51188969 0.19308622]
  [0.47621652 0.85555011 0.8421437  0.19447226 0.39324206]
  [0.52466284 0.37262377 0.77747227 0.66431809 0.13433683]]]
the array d [[[1.47390215 1.17515797 1.61892728 1.92184846 1.36711341]
  [1.09697434 1.97069412 1.97264883 1.36063071 1.47675032]
  [1.12272062 1.44136392 1.86437622 1.33154656 1.67765695]]

 [[1.36862302 1.50863563 1.12811749 1.51188969 1.19308622]
  [1.47621652 1.85555011 1.8421437  1.19447226 1.39324206]
  [1.52466284 1.37262377 1.77747227 1.66431809 1.13433683]]]



### 12. Multiply a and c. Assign the result to e.


In [30]:
### [your code here]
e = a * c
print("Result of a * c:", e)

Result of a * c: [[[0.47390215 0.17515797 0.61892728 0.92184846 0.36711341]
  [0.09697434 0.97069412 0.97264883 0.36063071 0.47675032]
  [0.12272062 0.44136392 0.86437622 0.33154656 0.67765695]]

 [[0.36862302 0.50863563 0.12811749 0.51188969 0.19308622]
  [0.47621652 0.85555011 0.8421437  0.19447226 0.39324206]
  [0.52466284 0.37262377 0.77747227 0.66431809 0.13433683]]]




### 13. Does e equal to a? Why or why not?


In [31]:

#yes, This happens because of the Multiplicative Identity Property in mathematics: multiplying any number by \(1\) leaves that number unchanged (\(x \times 1 = x\)).




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [32]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

# Print the results to verify
print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 1.9726488317621511
Min value in d: 1.0969743410394608
Mean value in d: 1.4939234134973616



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [33]:
### [your code here]
f = np.empty(d.shape)
f

array([[[0.47390215, 0.17515797, 0.61892728, 0.92184846, 0.36711341],
        [0.09697434, 0.97069412, 0.97264883, 0.36063071, 0.47675032],
        [0.12272062, 0.44136392, 0.86437622, 0.33154656, 0.67765695]],

       [[0.36862302, 0.50863563, 0.12811749, 0.51188969, 0.19308622],
        [0.47621652, 0.85555011, 0.8421437 , 0.19447226, 0.39324206],
        [0.52466284, 0.37262377, 0.77747227, 0.66431809, 0.13433683]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:

import numpy as np

# 1. Start by setting everything to 50 (handles the mean case safely)
f = np.full(d.shape, 50.0)

# 2. Fill the ranges (excluding min and max using strict inequalities)
f[(d > d_min) & (d < d_mean)] = 25.0
f[(d > d_mean) & (d < d_max)] = 75.0

# 3. Explicitly overwrite the single min and max points last
f[d == d_min] = 0.0
f[d == d_max] = 100.0

print(f)



[[[ 25.  25.  75.  75.  25.]
  [  0.  75. 100.  25.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[ 25.  75.  25.  75.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [40]:
### [your code here]
print ("d:", d)
print ("f:", f)

d: [[[1.47390215 1.17515797 1.61892728 1.92184846 1.36711341]
  [1.09697434 1.97069412 1.97264883 1.36063071 1.47675032]
  [1.12272062 1.44136392 1.86437622 1.33154656 1.67765695]]

 [[1.36862302 1.50863563 1.12811749 1.51188969 1.19308622]
  [1.47621652 1.85555011 1.8421437  1.19447226 1.39324206]
  [1.52466284 1.37262377 1.77747227 1.66431809 1.13433683]]]
f: [[[ 25.  25.  75.  75.  25.]
  [  0.  75. 100.  25.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[ 25.  75.  25.  75.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]